import socket                                                                                                                                                                                                                              
                                                                                                                                                                                                                                           
max_port = 65535                                                                                                                                                                                                                           
min_port = 1                                                                                                                                                                                                                               
print("IPアドレスを入れてください")                                                                                                                                                                                                        
target_host = input(":")                                                                                                                                                                                                                   
                                                                                                                                                                                                                                           
for port in range(min_port, max_port):                                                                                                                                                                                                     
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)                                                                                                                                                                               
    return_code = sock.connect_ex((target_host, port))                                                                                                                                                                                     
    sock.close()                                                                                                                                                                                                                           
                                                                                                                                                                                                                                           
    if return_code == 0:                                                                                                                                                                                                                   
        print("Port %d open!" % (port))                                                                                                                                                                                                    
                                                                                                                                                                                                                                           
print("Complete!")                                                                                                                                                                                                                         
                     
